<?php

require_once 'Dase/DBO.php';

/*
 * DO NOT EDIT THIS FILE
 * it is auto-generated by the
 * script 'bin/class_gen.php
 * 
 */

class Dase_DBO_Autogen_Collection extends Dase_DBO 
{
	function __construct($assoc = false) 
	{
		parent::__construct( 'collection',  array('ascii_id','collection_name','created','description','is_public','path_to_media_files','updated','visibility'));
		if ($assoc) {
			foreach ( $assoc as $key => $value) {
				$this->$key = $value;
			}
		}
	}
}