<?php

require_once 'Dase/DBO.php';

/*
 * DO NOT EDIT THIS FILE
 * it is auto-generated by the
 * script 'bin/class_gen.php
 * 
 */

class Dase_DBO_Autogen_ItemLink extends Dase_DBO 
{
	function __construct($assoc = false) 
	{
		parent::__construct( 'item_link',  array('href','item_unique','length','rel','title','type'));
		if ($assoc) {
			foreach ( $assoc as $key => $value) {
				$this->$key = $value;
			}
		}
	}
}