<?php

require_once 'Dase/DBO.php';

/*
 * DO NOT EDIT THIS FILE
 * it is auto-generated by the
 * script 'bin/class_gen.php
 * 
 */

class Dase_DBO_Autogen_ItemRelation extends Dase_DBO 
{
	function __construct($assoc = false) 
	{
		parent::__construct( 'item_relation',  array('child_serial_number','collection_ascii_id','item_type_relation_id','parent_serial_number'));
		if ($assoc) {
			foreach ( $assoc as $key => $value) {
				$this->$key = $value;
			}
		}
	}
}