<?php

require_once 'Dase/DBO.php';

/*
 * DO NOT EDIT THIS FILE
 * it is auto-generated by the
 * script 'bin/class_gen.php
 * 
 */

class Dase_DBO_Autogen_Item extends Dase_DBO 
{
	public function __construct($db,$assoc = false) 
	{
		parent::__construct($db,'item', array('collection_id','collection_name','comments_count','comments_updated','content_length','created','created_by_eid','item_type_ascii_id','item_type_id','item_type_name','p_collection_ascii_id','p_remote_media_host','serial_number','status','updated'));
		if ($assoc) {
			foreach ( $assoc as $key => $value) {
				$this->$key = $value;
			}
		}
	}
}