<?php

require_once 'Dase/DBO.php';

/*
 * DO NOT EDIT THIS FILE
 * it is auto-generated by the
 * script 'bin/class_gen.php
 * 
 */

class Dase_DBO_Autogen_MediaValue extends Dase_DBO 
{
	function __construct($assoc = false) 
	{
		parent::__construct( 'media_value',  array('media_attribute_id','media_file_id','text'));
		if ($assoc) {
			foreach ( $assoc as $key => $value) {
				$this->$key = $value;
			}
		}
	}
}