<?php

require_once 'Dase/DBO.php';

/*
 * DO NOT EDIT THIS FILE
 * it is auto-generated by the
 * script 'bin/class_gen.php
 * 
 */

class Dase_DBO_Autogen_SearchCache extends Dase_DBO 
{
	function __construct($assoc = false) 
	{
		parent::__construct( 'search_cache',  array('is_stale','cb_id','sort_by','exact_search','attribute_id','dase_user_id','item_id_string','timestamp','search_md5','refine','collection_id_string','query'));
		if ($assoc) {
			foreach ( $assoc as $key => $value) {
				$this->$key = $value;
			}
		}
	}
}