<?php

require_once 'Dase/DBO.php';

/*
 * DO NOT EDIT THIS FILE
 * it is auto-generated by the
 * script 'bin/class_gen.php
 * 
 */

class Dase_DBO_Autogen_Tag extends Dase_DBO 
{
	function __construct($assoc = false) 
	{
		parent::__construct( 'tag',  array('is_public','admin_collection_id','dase_user_id','visibility','eid','type','created','ascii_id','background','description','name'));
		if ($assoc) {
			foreach ( $assoc as $key => $value) {
				$this->$key = $value;
			}
		}
	}
}