<?php

require_once 'Dase/DBO.php';

/*
 * DO NOT EDIT THIS FILE
 * it is auto-generated by the
 * script 'bin/class_gen.php
 * 
 */

class Dase_DBO_Autogen_ItemTypeRelation extends Dase_DBO 
{
	function __construct($assoc = false) 
	{
		parent::__construct( 'item_type_relation',  array('child_type_ascii_id','collection_ascii_id','parent_type_ascii_id','title'));
		if ($assoc) {
			foreach ( $assoc as $key => $value) {
				$this->$key = $value;
			}
		}
	}
}