<?php

require_once 'Dase/DBO.php';

/*
 * DO NOT EDIT THIS FILE
 * it is auto-generated by the
 * script 'bin/class_gen.php
 * 
 */

class Dase_DBO_Autogen_CategoryScheme extends Dase_DBO 
{
	function __construct($assoc = false) 
	{
		parent::__construct( 'category_scheme',  array('applies_to','created','created_by_eid','description','fixed','name','uri'));
		if ($assoc) {
			foreach ( $assoc as $key => $value) {
				$this->$key = $value;
			}
		}
	}
}