<?php

require_once 'Dase/DBO.php';

/*
 * DO NOT EDIT THIS FILE
 * it is auto-generated by the
 * script 'bin/class_gen.php
 * 
 */

class Dase_DBO_Autogen_Content extends Dase_DBO 
{
	function __construct($assoc = false) 
	{
		parent::__construct( 'content',  array('item_id','p_collection_ascii_id','p_serial_number','text','type','update_by_eid','updated'));
		if ($assoc) {
			foreach ( $assoc as $key => $value) {
				$this->$key = $value;
			}
		}
	}
}