<?php

require_once 'Dase/DBO.php';

/*
 * DO NOT EDIT THIS FILE
 * it is auto-generated by the
 * script 'bin/class_gen.php
 * 
 */

class Dase_DBO_Autogen_DaseUser extends Dase_DBO 
{
	function __construct($assoc = false) 
	{
		parent::__construct( 'dase_user',  array('has_access_exception','current_search_cache_id','max_items','template_composite','backtrack','current_collections','last_action','last_item','display','last_cb_access','cb','name','eid'));
		if ($assoc) {
			foreach ( $assoc as $key => $value) {
				$this->$key = $value;
			}
		}
	}
}