<?php

require_once 'Dase/DBO.php';

/*
 * DO NOT EDIT THIS FILE
 * it is auto-generated by the
 * script 'bin/class_gen.php
 * 
 */

class Dase_DBO_Autogen_ItemAsAtom extends Dase_DBO 
{
	function __construct($assoc = false) 
	{
		parent::__construct( 'item_as_atom',  array('item_id','item_type_ascii_id','relative_url','updated','xml'));
		if ($assoc) {
			foreach ( $assoc as $key => $value) {
				$this->$key = $value;
			}
		}
	}
}