<?php

require_once 'Dase/DBO.php';

/*
 * DO NOT EDIT THIS FILE
 * it is auto-generated by the
 * script 'bin/class_gen.php
 * 
 */

class Dase_DBO_Autogen_Item extends Dase_DBO 
{
	public function __construct($db,$assoc = false) 
	{
		parent::__construct($db,'item', array('item_type_id','collection_id','p_collection_ascii_id','created_by_eid','status','updated','comments_updated','comments_count','created','serial_number','item_type_ascii_id','item_type_name','collection_name','p_remote_media_host'));
		if ($assoc) {
			foreach ( $assoc as $key => $value) {
				$this->$key = $value;
			}
		}
	}
}