<?php

require_once 'Dase/DBO.php';

/*
 * DO NOT EDIT THIS FILE
 * it is auto-generated by the
 * script 'bin/class_gen.php
 * 
 */

class Dase_DBO_Autogen_SearchTable extends Dase_DBO 
{
	function __construct($assoc = false) {
		parent::__construct( 'search_table',  array('collection_id','item_id','status_id','updated','value_text'));
		if ($assoc) {
			foreach ( $assoc as $key => $value) {
				$this->$key = $value;
			}
		}
	}
}