<?php

require_once 'Dase/DBO.php';

/*
 * DO NOT EDIT THIS FILE
 * it is auto-generated by the
 * script 'bin/class_gen.php
 * 
 */

class Dase_DBO_Autogen_Value extends Dase_DBO 
{
	function __construct($assoc = false) {
		parent::__construct( 'value',  array('attribute_id','item_id','value_text','value_text_md5'));
		if ($assoc) {
			foreach ( $assoc as $key => $value) {
				$this->$key = $value;
			}
		}
	}
}