<?php

require_once 'Dase/DBO.php';

/*
 * DO NOT EDIT THIS FILE
 * it is auto-generated by the
 * script 'bin/class_gen.php
 * 
 */

class Dase_DBO_Autogen_ValueRevisionHistory extends Dase_DBO 
{
	function __construct($assoc = false) 
	{
		parent::__construct( 'value_revision_history',  array('added_text','deleted_text','timestamp','collection_ascii_id','attribute_name','item_serial_number','dase_user_eid'));
		if ($assoc) {
			foreach ( $assoc as $key => $value) {
				$this->$key = $value;
			}
		}
	}
}