<?php

require_once 'Dase/DBO.php';

/*
 * DO NOT EDIT THIS FILE
 * it is auto-generated by the
 * script 'bin/class_gen.php
 * 
 */

class Dase_DBO_Autogen_WebServiceUser extends Dase_DBO 
{
	function __construct($assoc = false) 
	{
		parent::__construct( 'web_service_user',  array('auth_level','name','token'));
		if ($assoc) {
			foreach ( $assoc as $key => $value) {
				$this->$key = $value;
			}
		}
	}
}