<?php

require_once 'Dase/DB/Object.php';

/*
 * DO NOT EDIT THIS FILE
 * it is auto-generated by the
 * script 'bin/class_gen.php
 * 
 */

class Dase_DB_Autogen_TagType extends Dase_DB_Object 
{
	function __construct($assoc = false) {
		parent::__construct( 'tag_type',  array('ascii_id','name'));
		if ($assoc) {
			foreach ( $assoc as $key => $value) {
				$this->$key = $value;
			}
		}
	}
}