<?php

require_once 'Dase/DB/Object.php';

/*
 * DO NOT EDIT THIS FILE
 * it is auto-generated by the
 * script 'bin/class_gen.php
 * 
 */

class Dase_DB_Autogen_CollectionManager extends Dase_DB_Object 
{
	function __construct($assoc = false) {
		parent::__construct( 'collection_manager',  array('auth_level','collection_ascii_id','dase_user_eid','expiration'));
		if ($assoc) {
			foreach ( $assoc as $key => $value) {
				$this->$key = $value;
			}
		}
	}
}