<?php

require_once 'Dase/DBO.php';

/*
 * DO NOT EDIT THIS FILE
 * it is auto-generated by the
 * script 'bin/class_gen.php
 * 
 */

class Dase_DB_Autogen_TagItem extends Dase_DBO 
{
	function __construct($assoc = false) {
		parent::__construct( 'tag_item',  array('annotation','item_id','p_collection_ascii_id','p_serial_number','size','sort_order','tag_id','updated'));
		if ($assoc) {
			foreach ( $assoc as $key => $value) {
				$this->$key = $value;
			}
		}
	}
}